name: optimal_hrv_bloc
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  accordion: ^2.1.2
  authentication_repository:
    path: packages/authentication_repository
  bloc: ^8.0.2
  bloc_test: ^9.0.2
  camera: ^0.9.4+4
  cloud_firestore: ^3.1.8
  equatable: ^2.0.3
  firebase_storage: ^10.2.9
  flow_builder: ^0.0.4
  flutter:
    sdk: flutter
  
  flutter_bloc: ^8.0.1
  font_awesome_flutter: ^9.1.0
  form_inputs:
    path: packages/form_inputs
  formz: ^0.4.0
  google_fonts: ^2.1.0
  image_picker: ^0.8.4+10
  intl: ^0.17.0
  meta: ^1.3.0
  very_good_analysis: ^2.3.0
  google_sign_in: ^5.2.4


dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  mocktail: ^0.2.0
  flutter_native_splash: ^2.1.3+1
  flutter_launcher_icons: "^0.9.2"


flutter_native_splash:
  color: "#FFFFFF"
  image: assets/HeartLogo.png
  android_12:
    image: assets/HeartLogo.png
  android: true
  ios: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/HeartLogo.png"
  

flutter:
  uses-material-design: true
  assets:
    - assets/